### DISCUSSION TITLE
How to use `!include` keyword?

### DISCUSSION THREAD

**Discussion by artinnok** [structurizr/onpremises#114] [Q&A]
Hello @simonbrowndotje,

I have a following setup:
- `docker-compose.yml`
```yml
services:
  structurizr-onpremise:
    image: structurizr/onpremises:latest
    container_name: structurizr-onpremise
    ports:
      - "8080:8080"
    volumes:
      - "/path/to/structurizr:/usr/local/structurizr"
```
- `containers.dsl`
```dsl

webapp = container "Web Application" {
    description "Delivers the static content and the JavaScript application."
    technology "React"
}
database = container "Database" {
    description "Stores information regarding the users and content."
    technology "PostgreSQL"
}
```
- At address `http://localhost:8080/workspace/2/dsl` I used DSL editor to define main file like that:
```dsl
workspace "Name" "Description" {

    model {
        softwareSystem = softwareSystem "Software System" {
            !include /usr/local/structurizr/2/containers.dsl
        }
    }

    configuration {
        scope softwaresystem
    }
}
```
But nothing is happen :worried:.

What I'm doing wrong?
Could you please provide an example how to use `!include` keyword?

Thanks,
Artem
