### ISSUE TITLE
Thumbnails are not created

### ISSUE THREAD

**Issue by jtbuk** [structurizr/onpremises#106]
### Description

Currently when using structurizr on-prem thumbnails are attempting to load however the files are not being written to disk, and the on-prem web server responds with 404.

This happens for the workspace thumbnails, as-well as thumbnails for individual views

![image](https://github.com/structurizr/onpremises/assets/107467488/8bf50f89-767e-4fc5-968b-6f5dd93b85b5)

### Steps to reproduce

Run on-prem via docker e.g. docker-compose.yml file:

```
name: structurizr

services:
  # https://docs.structurizr.com/onpremises
  on-prem:
    container_name: structurizr
    restart: always
    image: structurizr/onpremises
    volumes:
      - ./structurizr:/usr/local/structurizr
    ports:
      - 9091:8080
```

Publish a workspace to it via the CLI.

Navigate to the workspace, see the thumbnails are not being rendered.

The contents of my `structurizr.properties` file is as follows:
`structurizr.data=file`

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free
