### ISSUE TITLE
Images don't using cdnUrl variable

### ISSUE THREAD

**Issue by arnaudroubinet** [structurizr/onpremises#130]
### Expected

Having the onpremises installation behind a revers proxy and set structurizr.url=http://mydomain/structurizr
Open http://mydomain/structurizr

Html, JS and images are loaded using http://mydomain/structurizr path

### Actual

Some files don't use structurizrConfiguration.cdnUrl (and therefore not structurizr.url).

![image](https://github.com/user-attachments/assets/b3b75233-2cc5-463c-bc10-eb7b9c1c2e2a)

![image](https://github.com/user-attachments/assets/3cd9b622-50f5-4673-a5a7-fda1fdafb5c5)

### Steps to reproduce
```
services:
  structurizr:
    image: structurizr/onpremises
    container_name: structurizr
    restart: always
    volumes:
      - /lsf/structurizr:/usr/local/structurizr
    environment:
      - STRUCTURIZR_ENCRYPTION=myencryptionkey
      - VIRTUAL_HOST=mydomain
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/structurizr/
      - VIRTUAL_DEST=/
    expose:
      - 8080
    ports:
      - 8123:8080
    networks:
      - commonNetwork
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/var/run/podman/podman.sock:/tmp/docker.sock:ro"
    networks:
      - commonNetwork
networks:
  commonNetwork:
    external: true
```
Open http://mydomain/structurizr

### Version/build information

Structurizr on-premises installation
Build 2024.06.25

### Severity

Major

### Priority

I have no budget and there's no rush, please fix this for free

### More information

Example from prelude.jspf

![image](https://github.com/user-attachments/assets/d43ac0d8-0dbf-427f-80db-fa67f7656d0b)
![image](https://github.com/user-attachments/assets/2d5d3ae2-bc0e-456a-8f4b-eef8a2fea778)
