### ISSUE TITLE
Documentation not working in docker image 3196

### ISSUE THREAD

**Issue by SaschaWeisenberger** [structurizr/onpremises#80]
### Description

The build 3194 is still working, but from 3196 on the documentaion page is not working. There is only an empty page.
In the browser console I can see `GET http://localhost:8081/workspace/5/documentation net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)`

### Steps to reproduce

execute docker compose file

```yaml
version: '3.8'

services:
  structurizree:
    container_name: structurizree
    pull_policy: always
    restart: always
    image: structurizr/onpremises:3196
    ports:
    - 8081:8080
    volumes:
    - ./data/:/usr/local/structurizr
```

create a workspace and push a workspace.dsl with structurizr cli

### Severity

Minor

### Priority

Low

### Resolution

I have no budget and there's no rush, please fix this for free
